"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from pathlib import Path

from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$pg12i4)m^s+1ukk#(&-gu4pqq2beh*)t-nnpdm-*04$6dg!g3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ally',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Product Service Configuration
PRODUCTS_FILE = os.environ.get(
    'PRODUCTS_FILE',
    str(BASE_DIR / 'ally' / 'data' / 'asin_data_filled.csv')
)

COMPETITORS_FILE = os.environ.get(
    'COMPETITORS_FILE',
    str(BASE_DIR / 'ally' / 'data' / 'synthetic_competitor_products.csv')
)

GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY', 'defaults-on-in-private-repo')
if not GOOGLE_API_KEY:
    raise ValueError("GOOGLE_API_KEY require. Please set your environment variable to a valid GOOGLE_API_KEY.")
os.environ['GOOGLE_API_KEY'] = GOOGLE_API_KEY

OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', 'sk-not-setup')
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', 'sk-not-setup')
os.environ['ANTHROPIC_API_KEY'] = ANTHROPIC_API_KEY

AGENT_DEBUG = True if os.environ.get('AGENT_DEBUG', "False").lower() in ["true", "yes", "y", "1"] else False
print(f"Agent debugging: {AGENT_DEBUG}")

# Custom logging filter to exclude litellm event loop errors
class IgnoreLitellmEventLoopFilter(logging.Filter):
    def filter(self, record):
        # Filter out the litellm event loop error
        if 'is bound to a different event loop' in str(record.msg):
            return False
        if 'litellm_core_utils' in str(record.pathname):
            if 'Task exception was never retrieved' in str(record.msg):
                return False
        return True


# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'ignore_litellm': {
            '()': IgnoreLitellmEventLoopFilter,
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': 'verbose',
            'level': 'INFO',
            'filters': ['ignore_litellm'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'ally': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
